parameters:
  - name: ruleAppName
    type: string
    default: 'N/A'

trigger: none

jobs:
- template: catalogSourced-TestAndPromote.yml
  parameters:
    RuleAppName: ${{ parameters.ruleAppName }}
    SourceCatalogName: DEV
    DestinationCatalogName: UAT
    SourceLabel: LIVE
    DestinationLabel: LIVE
    
